### PR TITLE
Add cli usage

### PR DESCRIPTION
**Pull request by IgnisDa**
Reference #9

### CODE REVIEW

**Comment by IgnisDa** [comment]
Added tests for the scripts. At the moment the output is not pretty printed. We might have to do something about that. Maybe open a new issue?

**Comment by IgnisDa** [comment]
Reference #9

**Comment by IgnisDa** [comment]
Hello @hedythedev, it has been 2 weeks since I opened this PR. Can I have an update?

**Comment by hedythedev** [comment]
Extremely sorry about the delay @IgnisDa, it was mainly due to [this issue](https://github.com/huchenme/github-trending-api/issues/130), so I'm still working on which alternative URL to use, and I'm afraid this will have to be put on hold until there is a working alternative. In the meantime, maybe you can rename `cli.py` to `__main__.py` so that the CLI can be ran using `python -m gtrending` how does that sound? Thank you for your work so far.

As to the output, I don't think it's too much of a problem, and I will open a new issue after this is merged, because the output can be piped to programs such as jq to be further processed.

**Comment by hedyhli** [comment]
Hey I'm sorry for my slow response but I realized I actually had a pending review and forgot to submit it. Since you've removed your assignment I'll let @willtryagain work on this.

**Comment by willtryagain** [comment]
@hedyhli what else is left to be completed before this  can be merged? @IgnisDa seems to have done it all

**Comment by hedyhli** [comment]
> @hedyhli what else is left to be completed before this can be merged? @IgnisDa seems to have done it all

@willtryagain Not too much left, but there's a few things that needs to be fixed. If you'd like to reference their implementation feel free to take inspiration and commit on your PR (or open a new one) and I can review there.

**Pull request closed without merging**
